import { getLocale } from '@/store/localeStore'

const zhText = {
  common: {
    loading: '加载中...',
    unknownError: '系统异常，请稍后重试',
    operationFailed: '操作失败，请稍后重试',
    delete: '删除',
    cancel: '取消',
    save: '保存',
    confirm: '确定',
    edit: '编辑',
    preview: '预览',
    create: '新建',
    add: '添加',
    retry: '重试',
    reloadPage: '刷新页面',
    loadingData: '加载数据中...',
    noData: '暂无数据',
    language: '语言',
    chinese: '中文',
    english: '英文',
    invalidRequest: '请求参数无效',
    authExpired: '登录已过期，请重新登录',
    authInvalid: '身份认证失败，请重新登录',
    permissionDenied: '无权限执行此操作',
    resourceNotFound: '请求资源不存在',
    requestTimeout: '请求超时，请稍后重试',
    conflictError: '数据冲突，请刷新后重试',
    validationFailed: '提交数据校验失败',
    tooManyRequests: '请求过于频繁，请稍后再试',
    serverError: '服务器异常，请稍后重试',
    gatewayError: '网关异常，请稍后重试',
    serviceUnavailable: '服务暂时不可用',
    responseTimeout: '服务响应超时',
    networkError: '网络连接失败，请检查网络',
  },
  layout: {
    appTitle: '企业 RAG',
    welcome: '欢迎，',
    menuChat: '智能问答',
    menuDocument: '文档管理',
    menuAgent: 'Agent 工作区',
    menuAdmin: '管理后台',
    menuDashboard: '数据面板',
    menuUsers: '用户管理',
    menuRoles: '角色管理',
    menuPermissions: '权限管理',
    profile: '个人信息',
    settings: '系统设置',
    logout: '退出登录',
  },
  auth: {
    loginSuccess: '登录成功',
    loginFailed: '登录失败，请检查账号密码',
    registerSuccess: '注册成功，请登录',
    registerFailed: '注册失败，请重试',
    logoutSuccess: '已退出登录',
    loginTitle: '企业级 RAG 系统',
    loginSubtitle: '智能问答，知识赋能',
    account: '账号',
    password: '密码',
    tenantId: '租户ID',
    login: '登录',
    register: '注册',
    createAccount: '创建账号',
    registerSubtitle: '加入企业 RAG 系统',
    noAccount: '还没有账号？',
    hasAccount: '已有账号？',
    goRegister: '立即注册',
    goLogin: '立即登录',
    demoHint: '演示账号: admin / Admin@123',
    confirmPassword: '确认密码',
    realName: '真实姓名',
    email: '邮箱',
    phone: '手机号',
    department: '部门',
    optionalPhone: '手机号（可选）',
    optionalDepartment: '所属部门（可选）',
    inputAccount: '请输入账号',
    inputPassword: '请输入密码',
    inputTenant: '请输入租户',
    inputConfirmPassword: '请确认密码',
    inputRealName: '请输入真实姓名',
    inputEmail: '请输入邮箱',
    accountMin: '账号至少3个字符',
    accountMax: '账号最多50个字符',
    accountPattern: '只能包含字母、数字、下划线',
    passwordMin: '密码至少6个字符',
    passwordStrong: '密码必须包含大小写字母、数字和特殊字符',
    passwordMismatch: '两次输入的密码不一致',
    emailInvalid: '邮箱格式不正确',
    phoneInvalid: '手机号格式不正确',
    realNameMax: '姓名最多50个字符',
  },
  chat: {
    pageTitle: '智能问答',
    emptyDescription: '暂无对话记录，开始提问吧！',
    inputPlaceholder: '输入问题... (Shift+Enter 换行，Enter 发送)',
    sending: '发送',
    generating: 'AI 正在思考...',
    loadingHistory: '加载会话记录中...',
    hint: '提示：本系统基于文档知识库回答问题，回答仅供参考',
    copySuccess: '已复制到剪贴板',
    citationPreview: '查看引用 [{index}]',
    sendFailed: '发送失败，请重试',
    deleteSuccess: '会话已删除',
    deleteFailed: '删除失败',
    titleUpdated: '会话标题已更新',
    titleUpdateFailed: '更新标题失败',
    regenerate: '重新生成',
    references: '参考来源：',
    ragV0Label: 'RAG V0 (基础版)',
    ragV1Label: 'RAG V1 (增强版)',
    costSeconds: '耗时',
  },
  document: {
    pageTitle: '文档管理',
    searchPlaceholder: '搜索文档名称',
    filterStatus: '筛选状态',
    uploadHint: '点击或拖拽文件到此区域上传',
    uploadSupport: '支持 PDF、Word、TXT 格式，单个文件最大 50MB',
    uploadSuccess: '文档上传成功',
    uploadFailed: '上传失败',
    deleteSuccess: '文档已删除',
    deleteFailed: '删除失败',
    oversizeError: '文件大小不能超过 50MB',
    typeError: '仅支持 PDF、Word、TXT 格式',
    previewTitle: '文档预览',
    previewDeveloping: '文档预览功能开发中...',
    totalDocs: '共 {total} 个文档',
    colName: '文档名称',
    colSize: '大小',
    colStatus: '状态',
    colUploadTime: '上传时间',
    colActions: '操作',
    pending: '待处理',
    processing: '处理中',
    completed: '已完成',
    failed: '失败',
    confirmDeleteTitle: '确认删除',
    confirmDeleteContent: '确定要删除文档 "{name}" 吗？此操作不可恢复。',
    fieldName: '文档名称：',
    fieldSize: '文件大小：',
    fieldUploadTime: '上传时间：',
  },
  agent: {
    pageTitle: 'Agent 工作区',
    pageDescription: '智能 Agent 可以自动选择工具、执行任务并生成结果。支持 RAG 搜索、数据查询、日志分析等功能。',
    inputPlaceholder: '输入您的需求，例如：查询上个月订单数量最多的产品',
    execute: '执行',
    intentTitle: '意图识别',
    intentType: '类型：',
    intentConfidence: '置信度：',
    intentReasoning: '推理：',
    executionFlow: '执行流程',
    totalCost: '总耗时: {seconds}s',
    emptyDescription: '输入需求并点击执行，Agent 将自动完成任务',
    taskCompleted: 'Agent 任务完成',
    executeFailed: 'Agent 执行失败',
    stepThinking: 'Thinking',
    stepAction: 'Action',
    stepObservation: 'Observation',
    stepFinal: 'Final Answer',
    toolLabel: '工具：',
  },
  adminDashboard: {
    title: '数据面板',
    apiTrend: 'API 使用趋势（最近7天）',
    v0Api: 'V0 接口',
    v1Api: 'V1 接口',
    docDistribution: '文档类型分布',
    docType: '文档类型',
    responseDistribution: '响应时间分布（秒）',
    requestCount: '请求数',
    topQuestions: '热门问题 TOP 5',
    rank: '排名',
    question: '问题',
    count: '次数',
    totalUsers: '总用户数',
    totalDocuments: '总文档数',
    totalChats: '总对话数',
    avgResponseTime: '平均响应时间',
    // Weekdays
    monday: '周一',
    tuesday: '周二',
    wednesday: '周三',
    thursday: '周四',
    friday: '周五',
    saturday: '周六',
    sunday: '周日',
    // Top questions
    topQuestion1: '房价下降的基本原则是什么？',
    topQuestion2: '如何进行文档上传？',
    topQuestion3: 'RAG V0 和 V1 有什么区别？',
    topQuestion4: '支持哪些文件格式？',
    topQuestion5: '如何管理会话历史？',
  },
  adminRole: {
    title: '角色管理',
    create: '新建角色',
    edit: '编辑角色',
    assignPermissions: '分配权限',
    deleteConfirm: '确定要删除角色 "{name}" 吗？',
    roleName: '角色名称',
    roleCode: '角色代码',
    description: '描述',
    userCount: '用户数',
    permissionCount: '权限数',
    totalRows: '共 {total} 条',
    inputRoleName: '请输入角色名称',
    inputRoleCode: '请输入角色代码',
    roleCodePattern: '仅支持小写字母和下划线',
    roleNamePlaceholder: '如：部门经理',
    roleCodePlaceholder: '如：dept_manager',
    descriptionPlaceholder: '角色描述（可选）',
    assignDrawerTitle: '为 "{name}" 分配权限',
    selectedPermissionCount: '已选择 {count} 个权限',
    loadingRolePermissions: '加载角色权限中...',
    loadingPermissions: '加载权限数据中...',
    emptyPermissions: '暂无权限数据',
    emptyPermissionsHint: '请检查后端权限是否已初始化',
    othersModule: '其他',
  },
  adminPermission: {
    title: '权限管理',
    create: '新建权限',
    edit: '编辑权限',
    code: '权限代码',
    name: '权限名称',
    description: '描述',
    roleCount: '关联角色数',
    moduleCount: '{count} 个权限',
    deleteConfirm: '确定要删除权限 "{name}" 吗？',
    inputCode: '请输入权限代码',
    inputName: '请输入权限名称',
    codePattern: '格式：模块.操作，如 user.create',
    codePlaceholder: '如：user.create',
    namePlaceholder: '如：创建用户',
    descriptionPlaceholder: '权限描述（可选）',
  },
  adminUser: {
    title: '用户管理',
    addUser: '添加用户',
    editUser: '编辑用户',
    createUser: '添加用户',
    assignedRoleCount: '当前已分配 {count} 个角色',
    assignRole: '分配角色',
    enable: '启用',
    disable: '禁用',
    userAdded: '用户已添加',
    addFailed: '添加失败',
    userUpdated: '用户信息已更新',
    updateFailed: '更新失败',
    userDeleted: '用户已删除',
    userDeleteFailed: '删除失败',
    userEnabled: '用户已启用',
    userDisabled: '用户已禁用',
    totalUsers: '共 {total} 个用户',
    account: '账号',
    realName: '真实姓名',
    email: '邮箱',
    department: '部门',
    status: '状态',
    createTime: '创建时间',
    actions: '操作',
    confirmDeleteTitle: '确认删除',
    confirmDeleteContent: '确定要删除该用户吗？',
    assignRoleDrawerTitle: '为 "{name}" 分配角色',
    inputAccount: '请输入账号',
    inputPassword: '请输入密码',
    inputRealName: '请输入真实姓名',
    inputEmail: '请输入邮箱',
    accountMin: '账号至少3个字符',
    accountPattern: '只能包含字母、数字、下划线',
    passwordMin: '密码至少6个字符',
    emailInvalid: '邮箱格式不正确',
    accountPlaceholder: '账号',
    passwordPlaceholder: '密码',
    realNamePlaceholder: '真实姓名',
    emailPlaceholder: '邮箱地址',
    phonePlaceholder: '手机号（可选）',
    departmentPlaceholder: '所属部门（可选）',
  },
  debug: {
    title: 'RBAC 调试信息',
    rolesApi: '角色接口',
    permissionsApi: '权限接口',
    apiError: '接口错误',
    status: '状态',
    success: '成功',
    count: '数量',
    tips: '调试建议',
    tips1: '打开浏览器开发者工具 (F12)',
    tips2: '查看 Console 标签页中的错误',
    tips3: '查看 Network 标签页中的接口调用：',
    tips4: '验证 localStorage 中的 JWT：',
  },
  feedback: {
    roleCreateSuccess: '角色创建成功',
    roleUpdateSuccess: '角色更新成功',
    roleDeleteSuccess: '角色删除成功',
    permissionAssignSuccess: '权限分配成功',
    permissionCreateSuccess: '权限创建成功',
    permissionUpdateSuccess: '权限更新成功',
    permissionDeleteSuccess: '权限删除成功',
    userRoleAssignSuccess: '角色分配成功',
    createFailed: '创建失败',
    updateFailed: '更新失败',
    deleteFailed: '删除失败',
    assignFailed: '分配失败',
  },
  session: {
    newChat: '新建对话',
    empty: '暂无会话记录',
    rename: '重命名',
    deleteConfirmTitle: '确认删除会话？',
    deleteConfirmContent: '确定要删除会话"{title}"吗？此操作不可恢复。',
    today: '今天',
    yesterday: '昨天',
    thisWeek: '过去7天',
    older: '更早',
  },
  errorBoundary: {
    title: '页面发生异常',
    subTitle: '请尝试刷新页面，如果问题持续出现请联系管理员。',
    details: '错误详情',
  },
} as const

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K]
}

type DeepStringWiden<T> = {
  [K in keyof T]: T[K] extends string ? string : DeepStringWiden<T[K]>
}

type UiTextSchema = DeepStringWiden<typeof zhText>

const enText: DeepPartial<UiTextSchema> = {
  common: {
    loading: 'Loading...',
    unknownError: 'System error. Please try again later.',
    operationFailed: 'Operation failed. Please try again later.',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    confirm: 'Confirm',
    edit: 'Edit',
    preview: 'Preview',
    create: 'Create',
    add: 'Add',
    retry: 'Retry',
    reloadPage: 'Reload page',
    loadingData: 'Loading data...',
    noData: 'No data',
    language: 'Language',
    chinese: 'Chinese',
    english: 'English',
    invalidRequest: 'Invalid request parameters',
    authExpired: 'Session expired. Please login again.',
    authInvalid: 'Authentication failed. Please login again.',
    permissionDenied: 'You do not have permission for this action',
    resourceNotFound: 'Requested resource was not found',
    requestTimeout: 'Request timed out. Please try again later.',
    conflictError: 'Data conflict. Please refresh and try again.',
    validationFailed: 'Submitted data validation failed',
    tooManyRequests: 'Too many requests. Please try again later.',
    serverError: 'Server error. Please try again later.',
    gatewayError: 'Gateway error. Please try again later.',
    serviceUnavailable: 'Service temporarily unavailable',
    responseTimeout: 'Service response timeout',
    networkError: 'Network connection failed. Please check your network.',
  },
  layout: {
    appTitle: 'Enterprise RAG',
    welcome: 'Welcome, ',
    menuChat: 'Chat',
    menuDocument: 'Documents',
    menuAgent: 'Agent Workspace',
    menuAdmin: 'Admin',
    menuDashboard: 'Dashboard',
    menuUsers: 'Users',
    menuRoles: 'Roles',
    menuPermissions: 'Permissions',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
  },
  auth: {
    loginSuccess: 'Login successful',
    loginFailed: 'Login failed. Please check your account and password.',
    registerSuccess: 'Registration successful. Please log in.',
    registerFailed: 'Registration failed. Please try again.',
    logoutSuccess: 'Logged out',
    loginTitle: 'Enterprise RAG Platform',
    loginSubtitle: 'Intelligent Q&A, powered by knowledge',
    account: 'Account',
    password: 'Password',
    tenantId: 'Tenant ID',
    login: 'Login',
    register: 'Register',
    createAccount: 'Create Account',
    registerSubtitle: 'Join Enterprise RAG',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    goRegister: 'Register now',
    goLogin: 'Login now',
    demoHint: 'Demo account: admin / Admin@123',
    confirmPassword: 'Confirm password',
    realName: 'Full name',
    email: 'Email',
    phone: 'Phone',
    department: 'Department',
    optionalPhone: 'Phone (optional)',
    optionalDepartment: 'Department (optional)',
    inputAccount: 'Please enter account',
    inputPassword: 'Please enter password',
    inputTenant: 'Please enter tenant',
    inputConfirmPassword: 'Please confirm password',
    inputRealName: 'Please enter full name',
    inputEmail: 'Please enter email',
    accountMin: 'Account must be at least 3 characters',
    accountMax: 'Account must be at most 50 characters',
    accountPattern: 'Only letters, numbers and underscore are allowed',
    passwordMin: 'Password must be at least 6 characters',
    passwordStrong: 'Password must include upper/lowercase letters, number and symbol',
    passwordMismatch: 'Passwords do not match',
    emailInvalid: 'Invalid email format',
    phoneInvalid: 'Invalid phone format',
    realNameMax: 'Name must be at most 50 characters',
  },
  chat: {
    pageTitle: 'Chat',
    emptyDescription: 'No conversation yet. Start asking questions.',
    inputPlaceholder: 'Type your question... (Shift+Enter for newline, Enter to send)',
    sending: 'Send',
    generating: 'AI is thinking...',
    loadingHistory: 'Loading conversation history...',
    hint: 'Tip: Answers are generated from your knowledge base and are for reference only.',
    copySuccess: 'Copied to clipboard',
    citationPreview: 'View reference [{index}]',
    sendFailed: 'Failed to send. Please try again.',
    deleteSuccess: 'Conversation deleted',
    deleteFailed: 'Delete failed',
    titleUpdated: 'Conversation title updated',
    titleUpdateFailed: 'Failed to update title',
    regenerate: 'Regenerate',
    references: 'References:',
    ragV0Label: 'RAG V0 (Basic)',
    ragV1Label: 'RAG V1 (Enhanced)',
    costSeconds: 'Duration',
  },
  document: {
    pageTitle: 'Document Management',
    searchPlaceholder: 'Search document name',
    filterStatus: 'Filter status',
    uploadHint: 'Click or drag files here to upload',
    uploadSupport: 'Supports PDF, Word, TXT. Max size 50MB per file',
    uploadSuccess: 'Document uploaded',
    uploadFailed: 'Upload failed',
    deleteSuccess: 'Document deleted',
    deleteFailed: 'Delete failed',
    oversizeError: 'File size cannot exceed 50MB',
    typeError: 'Only PDF, Word, TXT are supported',
    previewTitle: 'Document Preview',
    previewDeveloping: 'Document preview is under development...',
    totalDocs: 'Total {total} documents',
    colName: 'Name',
    colSize: 'Size',
    colStatus: 'Status',
    colUploadTime: 'Uploaded at',
    colActions: 'Actions',
    pending: 'Pending',
    processing: 'Processing',
    completed: 'Completed',
    failed: 'Failed',
    confirmDeleteTitle: 'Confirm delete',
    confirmDeleteContent: 'Delete document "{name}"? This action cannot be undone.',
    fieldName: 'Document name:',
    fieldSize: 'File size:',
    fieldUploadTime: 'Uploaded at:',
  },
  agent: {
    pageTitle: 'Agent Workspace',
    pageDescription: 'The smart agent can choose tools, execute tasks, and generate results automatically.',
    inputPlaceholder: 'Describe your task, e.g. find top-selling product of last month',
    execute: 'Execute',
    intentTitle: 'Intent Recognition',
    intentType: 'Type:',
    intentConfidence: 'Confidence:',
    intentReasoning: 'Reasoning:',
    executionFlow: 'Execution Flow',
    totalCost: 'Total cost: {seconds}s',
    emptyDescription: 'Enter a task and click Execute.',
    taskCompleted: 'Agent task completed',
    executeFailed: 'Agent execution failed',
    stepThinking: 'Thinking',
    stepAction: 'Action',
    stepObservation: 'Observation',
    stepFinal: 'Final Answer',
    toolLabel: 'Tool:',
  },
  adminDashboard: {
    title: 'Dashboard',
    apiTrend: 'API usage trend (last 7 days)',
    v0Api: 'V0 API',
    v1Api: 'V1 API',
    docDistribution: 'Document type distribution',
    docType: 'Document type',
    responseDistribution: 'Response time distribution (seconds)',
    requestCount: 'Requests',
    topQuestions: 'Top 5 popular questions',
    rank: 'Rank',
    question: 'Question',
    count: 'Count',
    totalUsers: 'Total users',
    totalDocuments: 'Total documents',
    totalChats: 'Total chats',
    avgResponseTime: 'Average response time',
    // Weekdays
    monday: 'Mon',
    tuesday: 'Tue',
    wednesday: 'Wed',
    thursday: 'Thu',
    friday: 'Fri',
    saturday: 'Sat',
    sunday: 'Sun',
    // Top questions
    topQuestion1: 'What are the basic principles of house price reduction?',
    topQuestion2: 'How to upload documents?',
    topQuestion3: 'What are the differences between RAG V0 and V1?',
    topQuestion4: 'What file formats are supported?',
    topQuestion5: 'How to manage conversation history?',
  },
  adminRole: {
    title: 'Role Management',
    create: 'Create role',
    edit: 'Edit role',
    assignPermissions: 'Assign permissions',
    deleteConfirm: 'Delete role "{name}"?',
    roleName: 'Role name',
    roleCode: 'Role code',
    description: 'Description',
    userCount: 'Users',
    permissionCount: 'Permissions',
    totalRows: 'Total {total} items',
    inputRoleName: 'Please enter role name',
    inputRoleCode: 'Please enter role code',
    roleCodePattern: 'Only lowercase letters and underscores are allowed',
    roleNamePlaceholder: 'e.g. Department Manager',
    roleCodePlaceholder: 'e.g. dept_manager',
    descriptionPlaceholder: 'Role description (optional)',
    assignDrawerTitle: 'Assign permissions for "{name}"',
    selectedPermissionCount: '{count} permissions selected',
    loadingRolePermissions: 'Loading role permissions...',
    loadingPermissions: 'Loading permissions...',
    emptyPermissions: 'No permissions',
    emptyPermissionsHint: 'Please check backend permission initialization',
    othersModule: 'Others',
  },
  adminPermission: {
    title: 'Permission Management',
    create: 'Create permission',
    edit: 'Edit permission',
    code: 'Permission code',
    name: 'Permission name',
    description: 'Description',
    roleCount: 'Related roles',
    moduleCount: '{count} permissions',
    deleteConfirm: 'Delete permission "{name}"?',
    inputCode: 'Please enter permission code',
    inputName: 'Please enter permission name',
    codePattern: 'Format: module.action, e.g. user.create',
    codePlaceholder: 'e.g. user.create',
    namePlaceholder: 'e.g. Create user',
    descriptionPlaceholder: 'Permission description (optional)',
  },
  adminUser: {
    title: 'User Management',
    addUser: 'Add user',
    editUser: 'Edit user',
    createUser: 'Create user',
    assignedRoleCount: '{count} roles assigned',
    assignRole: 'Assign roles',
    enable: 'Enable',
    disable: 'Disable',
    userAdded: 'User added',
    addFailed: 'Failed to add user',
    userUpdated: 'User updated',
    updateFailed: 'Update failed',
    userDeleted: 'User deleted',
    userDeleteFailed: 'Delete failed',
    userEnabled: 'User enabled',
    userDisabled: 'User disabled',
    totalUsers: 'Total {total} users',
    account: 'Account',
    realName: 'Name',
    email: 'Email',
    department: 'Department',
    status: 'Status',
    createTime: 'Created at',
    actions: 'Actions',
    confirmDeleteTitle: 'Confirm delete',
    confirmDeleteContent: 'Delete this user?',
    assignRoleDrawerTitle: 'Assign roles for "{name}"',
    inputAccount: 'Please enter account',
    inputPassword: 'Please enter password',
    inputRealName: 'Please enter name',
    inputEmail: 'Please enter email',
    accountMin: 'Account must be at least 3 characters',
    accountPattern: 'Only letters, numbers and underscores are allowed',
    passwordMin: 'Password must be at least 6 characters',
    emailInvalid: 'Invalid email format',
    accountPlaceholder: 'Account',
    passwordPlaceholder: 'Password',
    realNamePlaceholder: 'Full name',
    emailPlaceholder: 'Email address',
    phonePlaceholder: 'Phone (optional)',
    departmentPlaceholder: 'Department (optional)',
  },
  debug: {
    title: 'RBAC Debug Information',
    rolesApi: 'Roles API',
    permissionsApi: 'Permissions API',
    apiError: 'API error',
    status: 'Status',
    success: 'Success',
    count: 'Count',
    tips: 'Debug tips',
    tips1: 'Open browser developer tools (F12)',
    tips2: 'Check errors in Console tab',
    tips3: 'Check requests in Network tab:',
    tips4: 'Validate JWT in localStorage:',
  },
  feedback: {
    roleCreateSuccess: 'Role created successfully',
    roleUpdateSuccess: 'Role updated successfully',
    roleDeleteSuccess: 'Role deleted successfully',
    permissionAssignSuccess: 'Permissions assigned successfully',
    permissionCreateSuccess: 'Permission created successfully',
    permissionUpdateSuccess: 'Permission updated successfully',
    permissionDeleteSuccess: 'Permission deleted successfully',
    userRoleAssignSuccess: 'Roles assigned successfully',
    createFailed: 'Create failed',
    updateFailed: 'Update failed',
    deleteFailed: 'Delete failed',
    assignFailed: 'Assign failed',
  },
  session: {
    newChat: 'New chat',
    empty: 'No conversations',
    rename: 'Rename',
    deleteConfirmTitle: 'Delete conversation?',
    deleteConfirmContent: 'Delete conversation "{title}"? This cannot be undone.',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'Past 7 days',
    older: 'Earlier',
  },
  errorBoundary: {
    title: 'Page error',
    subTitle: 'Please try reloading the page. If this keeps happening, contact an administrator.',
    details: 'Error details',
  },
}

function getNestedValue(source: unknown, path: string[]): unknown {
  return path.reduce<unknown>((current, key) => {
    if (current && typeof current === 'object' && key in (current as Record<string, unknown>)) {
      return (current as Record<string, unknown>)[key]
    }
    return undefined
  }, source)
}

function resolveText(path: string[]): unknown {
  const locale = getLocale()
  if (locale === 'en-US') {
    const enValue = getNestedValue(enText, path)
    if (enValue !== undefined) {
      return enValue
    }
  }

  return getNestedValue(zhText, path)
}

function createTextProxy(path: string[]): unknown {
  return new Proxy(
    {},
    {
      get(_target, prop) {
        if (typeof prop !== 'string') return undefined
        const nextPath = [...path, prop]
        const value = resolveText(nextPath)

        if (typeof value === 'string' || value === undefined) {
          return value
        }

        return createTextProxy(nextPath)
      },
    }
  )
}

export const uiText = createTextProxy([]) as UiTextSchema

export function formatText(template: string, params: Record<string, string | number>): string {
  return Object.entries(params).reduce((result, [key, value]) => {
    return result.split(`{${key}}`).join(String(value))
  }, template)
}
